name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # For action testing you can also run this manually

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run build
        working-directory: "./apps/webapp"
        run: npm run build

      - name: Add Build Info
        working-directory: "./apps/webapp"
        run: | 
          date > build/builddate.txt
          git rev-parse --short HEAD > build/commit.txt

      - name: Deploy to Production
        working-directory: "./apps/webapp"
        if: github.ref == 'refs/heads/master'
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          mkdir -p ~/bin
          export PATH="${HOME}/bin:${PATH}"
          wget -O ~/bin/git-filter-repo https://raw.githubusercontent.com/newren/git-filter-repo/7b3e714b94a6e5b9f478cb981c7f560ef3f36506/git-filter-repo
          chmod +x ~/bin/git-filter-repo
  
          ls -la
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          git clone git@github.com:scribear/v.git
          git config --global user.email "angrave@illinois.edu"
          git config --global user.name "scribear-bot"
          cd v
          ls -la
          export SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`
          
          # git-filter-repo expects a fresh clone
          # git-filter-repo --path latest --invert-paths
          # TODO Need to debug why the above fails;
          # we can get error later when git push origin master
          # "fatal: 'origin' does not appear to be a git repository"
          
          # The following should not be required if git-filter-repo works
          git rm -rf latest
          git commit -m "Removing previous latest dir"
          
          mkdir -p latest
          mv ../dist/* latest
          git add latest
  
          git commit -m "Commit Deploy: ${SHORT_SHA}"
          git push origin master
